#server:  
#  port: ${PORT:8003}

logging:
  level:
   org.springframework:  debug

spring:
  application:
    name: service3

    
    
eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    